dist: xenial
language: python
python: 3.7

script:
  - mkdir build
  - pip install -r requirements.txt -t build/
  - cp serverless-es-rollover.py logging.ini -t build/
  - cd build && zip -r ../build ${TRAVIS_TAG}.zip *

deploy:
  provider: releases
  file: build-${TRAVIS_TAG}.zip
  skip-cleanup: true
  api_key:
    secure: Snbojz4kuZRVdPRltN7k9dYwRtnPYWOzEgtAXBLGh70HtGhPJSOSwrFohYgzU6gI84RPmUSqTS4joWIB7jZIEkv6jUkHAYH4WPAu0dfZlAXomIydfoFP4fX0IjmKzdCYaFL0BrXnocsrWS9HqQbi0AsefXm/pvgfT4JdTEYOlPNzezH0GivErugJseGqTVV6Pueze43y002ULPV8ZrW5hdScZ6NN+/Ikpvp5s7RQToW2FFG4Z0hcTeCvP6lhd6ObPcBBU2ZSI1qTze+tFsKI8zO+2MlDA5apmHpgY8o5BGeBuJgC2pUJozr96A7/7TCFpqOowKAJr90+wrdDDO6W79yce6wal7rQ9dlwYgwi9nBbQyt1XwOwa3OUzfa6YqLLAEL+fHqyMhEBsTfxKq7MwA+nc94126Z5s5hUXSu3MkdvzMQ62DbREVoO7LUfjUYtz4iW7ZCp37AznSiD3nckegfsAExczGkUZp+DF9x3lNmlihvcYYhrSwpK/ZihbYV7pTje4av2G0WaRACJyiHzS4mKDT7AdsOmI5aVoJjcMKkhMmO8O7niv3RDo0irZ905DEqGyqj6PXzke+2dO6odYeoher5v7HUpDLeWtQb/fBZ52Ewn8+uXx4apzdIjpLykMGH4YB0pPFcEOVg0cLs84Wy6k2hJ38yBatJSjIX1URI=
  on:
    repo: Tweddle-SE-Team/serverless-es-rollover
    tags: true
